data/code/sql/nl2sql/orders/qna.yaml
fms_sdg/databuilders/nl2sql/README.md
fms_sdg/databuilders/nl2sql/generate.py
fms_sdg/databuilders/nl2sql/nl2sql.yaml
fms_sdg/databuilders/nl2sql/sqlinstruct/__init__.py
fms_sdg/databuilders/nl2sql/sqlinstruct/models.py
fms_sdg/databuilders/nl2sql/sqlinstruct/pipeline.py
fms_sdg/databuilders/nl2sql/sqlinstruct/prompts/__init__.py
fms_sdg/databuilders/nl2sql/sqlinstruct/prompts/prompt_template.py
fms_sdg/databuilders/nl2sql/sqlinstruct/prompts/sql_prompts.py
fms_sdg/databuilders/nl2sql/task.py
fms_sdg/validators/nl2sql/sql_syntax_validator.py
tests/databuilders/test_nl2sql.py
tests/validators/test_nl2sql.py

Implementing NL2SQL pipelines via sqlinstruct providing an example of data configuration.

NL2SQL databuilder and data

---

fms_sdg/databuilders/api/README.md
fms_sdg/databuilders/api/api_function_checking.yaml
fms_sdg/databuilders/api/api_yes_no_detection.yaml
fms_sdg/databuilders/api/generate.py
fms_sdg/databuilders/api/task.py
fms_sdg/databuilders/api/utils.py
fms_sdg/validators/api.py

Adding initial commit for api data builder

---

fms_sdg/__main__.py
fms_sdg/databuilders/simple/generate.py
fms_sdg/generate_data.py
fms_sdg/generators/llm.py

It simplifies the process of adding your own custom arguments by allowing arguments to be specified as task-specific, databuilder-specific, or for the main process.

param fixes to make passing args to tasks and data builders easier

---

data/code/apis/glaive/README.md
data/code/apis/glaive/base_apis.yaml
data/code/apis/glaive/detection/multiple_apis/qna.yaml
data/code/apis/glaive/detection/single_api/qna.yaml
data/code/apis/glaive/detection/yes_no/qna.yaml
data/code/apis/glaive/sequencing/parallel_multiple/qna.yaml
data/code/apis/glaive/sequencing/parallel_single/qna.yaml

Adds a minimal set of examples / data for the API databuilder to the main repo. Will allow people to test the 5 API tasks locally

Adding minimal set of API examples to data dir

---

fms_sdg/base/task.py
fms_sdg/generate_data.py
fms_sdg/generators/genai.py
fms_sdg/generators/openai.py
fms_sdg/utils.py
fms_sdg/validators/lm_judge.py
tests/validators/test_lm_judge.py

Adds initial implementation of an LM as a judge for use with instruct lab tasks. In addition, adds a fix to the yaml data loader that supports a more intuitive file loading scheme which is needed for instruct lab tasks

initial implementation of lm as a judge

---

fms_sdg/generators/genai.py
fms_sdg/generators/llm.py
fms_sdg/generators/openai.py
fms_sdg/generators/vllm.py

Simplifying the lm generator code after a bug was found in the vllm implementation

Simplifying lm generators

---

fms_sdg/databuilders/nl2sql/generate.py
fms_sdg/databuilders/nl2sql/nl2sql.yaml
fms_sdg/validators/nl2sql/sql_execution_validator.py
fms_sdg/validators/nl2sql/sql_syntax_validator.py
tests/validators/test_nl2sql.py

Adding an additional validator for SQL code based on code execution against the provided schema.

feat: adding SQL execution validator.

---

fms_sdg/__main__.py
fms_sdg/databuilders/__init__.py
fms_sdg/generate_data.py
fms_sdg/utils.py

Adds ability to add new data builder directories outside of default location

Adding more flexible locations for data builders

---

fms_sdg/base/databuilder.py
fms_sdg/base/task.py
fms_sdg/databuilders/api/generate.py
fms_sdg/databuilders/nl2sql/generate.py
fms_sdg/databuilders/simple/generate.py
fms_sdg/generate_data.py
fms_sdg/validators/nl2sql/sql_syntax_validator.py

Adds ability to incrementally save by iterating over the call to `call_with_task_list` and saving each data point individually

Adding incremental saving

---

fms_sdg/databuilders/simple/utils.py

Bug fix in `simple` databuilder with logger

bug fix in simple data builder utils

---

data/code/apis/glaive/detection/multiple_apis/qna.yaml
data/code/apis/glaive/detection/single_api/qna.yaml
fms_sdg/databuilders/api/generate.py
fms_sdg/databuilders/api/task.py
fms_sdg/validators/api.py
tests/validators/test_api.py

Adds support for nested function calling within API tasks

Nested api

---

fms_sdg/__main__.py
fms_sdg/base/databuilder.py
fms_sdg/generate_data.py

This internalizes the execution of a task to be contained within a databuilder, thus moving more of the logic to how a databuilder runs to be self-contained within the databuilder. This will also make it easier to later distribute these tasks

updating data builder task execution

---

fms_dgt/base/block.py
fms_dgt/blocks/validators/lm_judge.py
tests/blocks/validators/test_lm_judge.py

Fixes lm_judge class to update with block design

Lm judge bug fix

---

fms_dgt/blocks/validators/lm_judge.py
tests/blocks/validators/test_lm_judge.py

Keeping block in line with base

sync change

---

docs/sdg_design.md

Updates docs to reflect blocks

Doc update

---

fms_dgt/base/databuilder.py
fms_dgt/base/datastore.py
fms_dgt/base/task.py
fms_dgt/datastores/default.py

Adds ability to save task details in datastore

update task saving in datastore

---

fms_dgt/base/task.py
fms_dgt/utils.py

Minor change to params for data store

datastore update

---

fms_dgt/base/block.py
fms_dgt/base/databuilder.py
fms_dgt/blocks/generators/genai.py
fms_dgt/blocks/generators/llm.py
fms_dgt/blocks/generators/openai.py
fms_dgt/blocks/generators/vllm.py
fms_dgt/utils.py
tests/blocks/generators/test_llm.py

Fixes a number of issues that have cropped up with generators

bug fixes to generators

---

fms_dgt/base/resource.py
fms_dgt/databuilders/api/generate.py

Changes a debug statement to an info statement

change to info

---

fms_dgt/databuilders/api/generate.py
fms_dgt/databuilders/simple/generate.py

Fixes way rouge validator was called in two databuilders

bug fix to rouge val

---

fms_dgt/databuilders/api/generate.py
fms_dgt/databuilders/simple/generate.py

additional fixes

---

fms_dgt/__main__.py
fms_dgt/base/databuilder.py
fms_dgt/base/task.py
fms_dgt/databuilders/simple/generate.py

Gives user more control of how many examples are drawn from seed / machine data on each iteration

add more control of batch size

---

fms_dgt/base/databuilder.py
fms_dgt/databuilders/api_transformation/generate.py

Bug fix to transformation pipeline

bug fix to transformation pipeline

---

fms_dgt/blocks/generators/llm.py
fms_dgt/blocks/generators/openai.py
fms_dgt/blocks/generators/vllm.py
fms_dgt/resources/api.py
tests/blocks/generators/test_llm.py

Misc fixes

---

fms_dgt/base/registry.py
fms_dgt/blocks/generators/llm.py
fms_dgt/blocks/generators/openai.py
tests/blocks/generators/test_llm.py

Allows automatic auto_chat_template to be applied when user specifies

Auto chat template

---

fms_dgt/base/registry.py

bug fix for vllm-remote

---

data/api_transformation/atis/.gitignore
data/api_transformation/atis/README.md
data/api_transformation/atis/qna.yaml
data/api_transformation/snips/.gitignore
data/api_transformation/snips/qna.yaml
fms_dgt/blocks/validators/lm_judge.py
fms_dgt/utils.py

bug fixes to registration

---

fms_dgt/databuilders/api_transformation/generate.py

api transformation: unify output structure

---

fms_dgt/blocks/validators/rouge.py
fms_dgt/databuilders/api/api_function_checking.yaml
fms_dgt/databuilders/api/generate.py
fms_dgt/databuilders/simple/generate.py
templates/databuilder/generate.py
tests/blocks/validators/test_rouge.py

Makes Rouge Filter a deduplicator (i.e., take a set of inputs and remove inputs that are too rouge similar)

Rouge dedup

---

fms_dgt/base/task.py
fms_dgt/databuilders/generation/api/task.py
fms_dgt/generate_data.py
tests/blocks/validators/test_api.py

minor changes

---

fms_dgt/__main__.py
fms_dgt/base/databuilder.py
fms_dgt/base/task.py
fms_dgt/databuilders/generation/api/api_function_checking.yaml
fms_dgt/databuilders/generation/api/api_yes_no_detection.yaml
fms_dgt/databuilders/generation/api/generate.py
fms_dgt/databuilders/generation/api/task.py
fms_dgt/generate_data.py
tests/blocks/validators/test_api.py

api updates

---

data/generation/pipeline/qna.yaml
fms_dgt/__main__.py
fms_dgt/base/pipeline.py
fms_dgt/generate_data.py
fms_dgt/index.py
fms_dgt/utils.py

update to path inclusion

---

data/generation/code/apis/glaive/detection/multiple_apis/qna.yaml
data/generation/code/apis/glaive/detection/single_api/qna.yaml
data/generation/code/apis/glaive/detection/yes_no/qna.yaml
data/generation/code/apis/glaive/sequencing/parallel_multiple/qna.yaml
data/generation/code/apis/glaive/sequencing/parallel_single/qna.yaml
fms_dgt/databuilders/generation/api/task.py

instruction format changes for api generation

---

fms_dgt/base/dataloader.py

bug fix to state

---

fms_dgt/base/block.py
fms_dgt/base/databuilder.py
fms_dgt/base/dataloader.py
fms_dgt/base/datastore.py
fms_dgt/base/registry.py
fms_dgt/base/task.py
fms_dgt/generate_data.py
fms_dgt/resources/api.py
fms_dgt/resources/genai.py
fms_dgt/resources/gpu.py
fms_dgt/resources/openai.py

Adding significantly more docstrings in the base classes. Also, one bug fix regarding key errors in DB initialization

Docstrings

---

fms_dgt/base/databuilder.py
fms_dgt/base/task.py
fms_dgt/generate_data.py
fms_dgt/index.py
fms_dgt/utils.py
tests/databuilders/test_databuilder_execution.py

Builder cfg loader

---

fms_dgt/generate_data.py
fms_dgt/utils.py

Relative paths

---

fms_dgt/utils.py

Better loading mechanism for nested configs

updating load_nested_config to be smarter

---

fms_dgt/__main__.py
tests/databuilders/test_databuilder_execution.py

test fixes

---

tests/databuilders/test_databuilder_execution.py

fix test dir del

---

fms_dgt/base/databuilder.py
fms_dgt/base/datastore.py
fms_dgt/base/task.py
fms_dgt/base/task_card.py
fms_dgt/datastores/default.py
fms_dgt/generate_data.py

Updates to datastore to simplify saving various data types

Datastore upd

---

fms_dgt/base/datastore.py
fms_dgt/datastores/multi.py

updates multi datastore to work with new datastore design

fix multi ds

---

data/generation/code/apis/glaive/detection/multiple_apis/qna.yaml
data/generation/code/apis/glaive/detection/single_api/qna.yaml
data/generation/code/apis/glaive/detection/yes_no/qna.yaml
data/generation/code/apis/glaive/sequencing/parallel_multiple/qna.yaml
data/generation/code/apis/glaive/sequencing/parallel_single/qna.yaml
data/generation/code/sql/nl2sql/orders/qna.yaml
data/generation/logical_reasoning/causal/qna.yaml
data/generation/pipeline/qna.yaml
data/generation/temporal_reasoning/qna.yaml
data/transformation/apis/atis/qna.yaml
data/transformation/apis/dstc8/qna.yaml
data/transformation/apis/multiwoz/qna.yaml
data/transformation/apis/snips/qna.yaml
data/transformation/apis/topv2/qna.yaml
fms_dgt/base/task.py
fms_dgt/base/task_card.py
fms_dgt/datastores/multi.py
fms_dgt/generate_data.py
fms_dgt/utils.py

User must explicitly specify task_name in their task file

adding task name

---

.gitignore
configs/all_api_tasks.yaml
fms_dgt/__main__.py
fms_dgt/base/datastore.py
fms_dgt/base/task.py
fms_dgt/base/task_card.py
fms_dgt/blocks/validators/__init__.py
fms_dgt/databuilders/generation/api/api_function_checking.yaml
fms_dgt/datastores/default.py
fms_dgt/generate_data.py
fms_dgt/utils.py

Allows config override to include task params

updating task config override

---

configs/all_api_tasks.yaml
fms_dgt/base/datastore.py
fms_dgt/base/task.py
fms_dgt/generate_data.py
fms_dgt/utils.py

Allows for tasks to be grouped in execution order

order tasks

---

fms_dgt/base/datastore.py
fms_dgt/base/task.py

adding final data type

---

fms_dgt/__main__.py
fms_dgt/base/task.py
fms_dgt/blocks/generators/llm.py

Adds more customization to saving final formatted data and auto chat template

Save final output

---

fms_dgt/base/task.py

Adds formal input/output data type for storing final outputs

input output formal

---

fms_dgt/blocks/validators/__init__.py

Saving validator failures as dict rather than as string

saving val failures as dict

---

fms_dgt/base/block.py
fms_dgt/base/databuilder.py
fms_dgt/base/task.py
fms_dgt/blocks/validators/__init__.py

add task cards to val

---

fms_dgt/blocks/validators/__init__.py
fms_dgt/databuilders/generation/api/api_function_checking.yaml

adding val ds name

---

fms_dgt/base/datastore.py
fms_dgt/datastores/default.py

add datastore reset to base

---

fms_dgt/base/databuilder.py

post proc fixes

---

fms_dgt/blocks/postprocessors/__init__.py
fms_dgt/blocks/postprocessors/datatrove/__init__.py
fms_dgt/blocks/postprocessors/datatrove/minhash_dedup.py

format output of datatrove block

---

fms_dgt/base/databuilder.py

add finish

---

fms_dgt/blocks/postprocessors/__init__.py
fms_dgt/blocks/postprocessors/datatrove/__init__.py

schema assert

---

fms_dgt/base/block.py
fms_dgt/base/databuilder.py
fms_dgt/base/datastore.py
fms_dgt/base/pipeline.py
fms_dgt/base/registry.py
fms_dgt/base/task.py
fms_dgt/blocks/__init__.py
fms_dgt/blocks/compositions/sequence.py
fms_dgt/blocks/postprocessors/__init__.py
fms_dgt/blocks/postprocessors/datatrove/__init__.py
fms_dgt/blocks/validators/__init__.py
fms_dgt/blocks/validators/lm_judge.py
fms_dgt/blocks/validators/rouge.py
fms_dgt/constants.py
fms_dgt/datastores/multi.py
fms_dgt/index.py
tests/blocks/validators/test_save_filtered.py

Allows blocks to specify a data schema, which facilitates saving of their outputs

Block schema

---

fms_dgt/blocks/validators/api.py
fms_dgt/databuilders/generation/api/generate.py
fms_dgt/utils.py
tests/blocks/validators/test_api.py

Adds more detailed function call checking

update schema checking

---

fms_dgt/blocks/validators/api.py
fms_dgt/databuilders/generation/api/utils.py

update simpler print

---

fms_dgt/base/task.py

Filters previous task cards based on build id

filter by build

---

fms_dgt/base/databuilder.py

Bug fix - filtering out tasks that are already complete

bug fix task completion

---

fms_dgt/generate_data.py

The current error message is confusing, as it is a nested error message due to how we load databuilders

unnest err

---

fms_dgt/base/task.py

update when close occurs

---

.env.example
fms_dgt/blocks/generators/genai.py
fms_dgt/blocks/generators/openai.py
fms_dgt/blocks/generators/watsonx.py
fms_dgt/resources/watsonx.py
pyproject.toml
tests/blocks/generators/test_llm.py

Supports #143 
Implements WatsonX AI foundation models based LLM generator block for broader use.

feat (WatsonX): WatsonX AI LLM generator block.

---

configs/all_api_tasks_parallel.yaml
fms_dgt/base/databuilder.py
fms_dgt/base/multiprocessing.py
fms_dgt/base/registry.py
fms_dgt/blocks/generators/vllm/server.py
fms_dgt/constants.py

change parallel to ray

---

fms_dgt/base/multiprocessing.py

bug fix empty configs

---

fms_dgt/base/multiprocessing.py
fms_dgt/blocks/generators/vllm/vllm_serve.py

Api key vllm server

---

fms_dgt/base/block.py
fms_dgt/base/multiprocessing.py
fms_dgt/base/registry.py
fms_dgt/blocks/generators/vllm/vllm_serve.py

Ray imp fix

---

fms_dgt/base/block.py
fms_dgt/base/multiprocessing.py
fms_dgt/blocks/validators/lm_judge.py

added nested block close

---

data/transformation/cot/qna.yaml
data/transformation/star/qna.yaml
fms_dgt/base/databuilder.py
fms_dgt/base/task.py
fms_dgt/blocks/generators/llm.py
fms_dgt/blocks/generators/vllm/vllm_serve.py
fms_dgt/blocks/trainers/__init__.py
fms_dgt/blocks/trainers/fms-hf-tuning/__init__.py
fms_dgt/blocks/trainers/fms-hf-tuning/run_fms_hf_tuning.py
fms_dgt/blocks/trainers/trainer.py
fms_dgt/blocks/validators/always_true.py
fms_dgt/constants.py
fms_dgt/databuilders/nonstandard/star/README.md
fms_dgt/databuilders/nonstandard/star/generate.py
fms_dgt/databuilders/nonstandard/star/star_transform.yaml
fms_dgt/databuilders/nonstandard/star/task.py
fms_dgt/databuilders/nonstandard/star/trainer_configs/ds_config.json
fms_dgt/databuilders/transformation/cot/README.md
fms_dgt/databuilders/transformation/cot/cot_transform.yaml
fms_dgt/databuilders/transformation/cot/generate.py
fms_dgt/databuilders/transformation/cot/task.py
fms_dgt/generate_data.py
fms_dgt/index.py
fms_dgt/utils.py

Adds trainer block and first implementation of STaR algorithm for a bootstrapping SDG process

Trainer Block / STaR

---

fms_dgt/base/task_card.py
fms_dgt/blocks/generators/llm.py
fms_dgt/blocks/trainers/fms-hf-tuning/run_fms_hf_tuning.py
fms_dgt/blocks/trainers/trainer.py
fms_dgt/generate_data.py
pyproject.toml

update for bug fixes

---

fms_dgt/base/databuilder.py
fms_dgt/base/datastore.py
fms_dgt/base/task.py

pointer datastore fix

---

fms_dgt/base/databuilder.py

add loose check

---

fms_dgt/base/databuilder.py

fix postprocessor

---

fms_dgt/index.py

Override upd

---

fms_dgt/base/block.py
fms_dgt/base/task_card.py
fms_dgt/blocks/utilities/field_map.py
fms_dgt/generate_data.py
tests/blocks/utilities/test_field_map.py

update how blocks call

---

fms_dgt/base/task.py

update final datastore

---

fms_dgt/databuilders/nonstandard/pipeline/generate.py
fms_dgt/index.py

pipeline fix

---

fms_dgt/base/databuilder.py
fms_dgt/blocks/compositions/sequence.py
fms_dgt/databuilders/generation/api/api_function_checking.yaml
fms_dgt/databuilders/generation/api/api_yes_no_detection.yaml
fms_dgt/databuilders/generation/simple/simple.yaml
fms_dgt/databuilders/nonstandard/pipeline/generate.py
fms_dgt/generate_data.py

simplify sequence spec

---

fms_dgt/base/task.py

update how default store name is determined

---

fms_dgt/index.py

Merge cfg fix

---

fms_dgt/blocks/generators/llm.py
fms_dgt/blocks/trainers/fms-hf-tuning/run_fms_hf_tuning.py
fms_dgt/blocks/trainers/trainer.py

Fixes bugs relating to Trainer / CachingLM

updates to fix bugs with trainer / caching llm

---

fms_dgt/blocks/generators/watsonx.py

Fixes a bug introduced by function signature changes in WatsonX generator.

fix (WatsonX): Broken invokation due to updated function signature.

---

fms_dgt/blocks/trainers/trainer.py
fms_dgt/utils.py

format fix

---

fms_dgt/blocks/trainers/fms-hf-tuning/run_fms_hf_tuning.py
fms_dgt/blocks/trainers/trainer.py

trainer fix

---

fms_dgt/blocks/generators/genai.py
fms_dgt/blocks/generators/llm.py
fms_dgt/blocks/generators/openai.py
fms_dgt/blocks/generators/vllm/vllm_in_proc.py
fms_dgt/blocks/generators/watsonx.py
tests/blocks/generators/test_llm.py

add multi outputs

---

fms_dgt/base/registry.py
fms_dgt/blocks/generators/llm.py
tests/blocks/generators/test_llm.py

force cache flag

---

fms_dgt/blocks/trainers/fms-hf-tuning/run_fms_hf_tuning.py

no run if done

---

fms_dgt/blocks/trainers/fms-hf-tuning/merge_model_utils.py
fms_dgt/blocks/trainers/fms-hf-tuning/post_process_adapters_vLLM.py
fms_dgt/blocks/trainers/fms-hf-tuning/run_fms_hf_tuning.py

update to auto merge

---

fms_dgt/__main__.py
fms_dgt/blocks/validators/api.py
fms_dgt/generate_data.py

Api logging

---

fms_dgt/databuilders/generation/simple/README.md
fms_dgt/databuilders/generation/simple/generate.py
fms_dgt/databuilders/generation/simple/simple.yaml
fms_dgt/databuilders/generation/simple/utils.py

- Defaults to using Mixtral's prompt template when models other than merlinite are used
- Change default backend to `watsonx`
- Update README

feat: updates to simple databuilder

---

fms_dgt/blocks/generators/llm.py
fms_dgt/blocks/generators/vllm/vllm_in_proc.py
tests/blocks/generators/test_llm.py

fix to max_length param

---

fms_dgt/blocks/validators/api.py

Api val bf

---

fms_dgt/databuilders/generation/api/api_function_checking.yaml
fms_dgt/databuilders/generation/api/api_yes_no_detection.yaml

change default

---

fms_dgt/blocks/validators/api.py
fms_dgt/databuilders/generation/api/api_function_checking.yaml
fms_dgt/databuilders/generation/api/generate.py
fms_dgt/databuilders/generation/api/task.py
tests/blocks/generators/test_llm.py
tests/blocks/validators/test_api.py

Function calling update

---

fms_dgt/base/databuilder.py
fms_dgt/blocks/generators/openai.py
fms_dgt/databuilders/generation/api/generate.py

speed up for func calling
